version: '3.6'
services:
  test:
    build:
      context: .
    volumes:
      - '.:/app'
    working_dir: /app
    command: dotnet test
  watch-test:
    build:
      context: .
    volumes:
      - '.:/app'
    working_dir: /app
    command: dotnet watch test
